---
- name: Create new databases
  become: true
  become_user: "{{ pg_user }}"
  postgresql_db:
    name: "{{ item.key }}"
  when: item.key != pg_user
  with_dict: "{{ credentials.users }}"
  tags: pg-databases

- name: Set postgres password with no expire date
  become: true
  become_user: "{{ pg_user }}"
  postgresql_user:
    name: "{{ pg_user }}"
    password: "{{ credentials.users[pg_user].password }}"
    expires: infinity

- name: Connect database, create users
  become: true
  become_user: "{{ pg_user }}"
  postgresql_user:
    name: "{{ item.key }}"
    password: "{{ item.value.password }}"
    expires: infinity
  when: item.key != pg_user
  with_dict: "{{ credentials.users }}"
  tags: pg-databases

- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted
  tags:  pg-databases

# https://docs.ansible.com/ansible/latest/modules/postgresql_privs_module.html?highlight=postgres
#- name: Grant all privileges
#  become: true
#  become_user: "{{ pg_user }}"
#  postgresql_privs:
#    db: "{{ item.key }}"
#    privs: ALL
#    type: database
#    role: "{{ item.key }}"
#  #when: item.key != pg_user
#  with_dict: "{{ credentials.users }}"
#  tags: pg-databases
