---
- name: Add userlist.txt file to pgbouncer
  template:
    src: pgbouncer/userlist.txt.j2
    dest: "/etc/pgbouncer/userlist.txt"
    owner: "{{ pg_user }}"
    group: "{{ pg_user }}"
  notify: reload pgbouncer

- name: Add pgbouncer.ini file
  template:
    src: pgbouncer/pgbouncer.ini.j2
    dest: "/etc/pgbouncer/pgbouncer.ini"
    owner: "{{ pg_user }}"
    group: "{{ pg_user }}"
  notify: restart pgbouncer
