---
- name: Add Security Ubuntu repository
  apt_repository:
    repo: deb http://security.ubuntu.com/ubuntu xenial-security main
    state: present
    filename: pgdg

- name: Ensure bash, OpenSSl, and libssl are the latest versions
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - bash
    - sysstat
    - openssl
    - aptitude
    - libssl-dev
    - libpq-dev
    - libpq5
    - python3-psycopg2
    - libicu55
