---
- name: Add environment file
  template:
    src: postgres/environment.j2
    dest: "/etc/postgresql/{{ pg_version }}/main/environment"
    owner: "{{ pg_user }}"
    group: "{{ pg_user }}"
  notify: reload postgresql
  tags: pg-config

- name: Add pg_ctl.conf file
  template:
    src: postgres/pg_ctl.conf.j2
    dest: "/etc/postgresql/{{ pg_version }}/main/pg_ctl.conf"
    owner: "{{ pg_user }}"
    group: "{{ pg_user }}"
  notify: reload postgresql
  tags: pg-config

- name: Add pg_hba.conf file
  template:
    src: postgres/pg_hba.conf.j2
    dest: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
    owner: "{{ pg_user }}"
    group: "{{ pg_user }}"
  notify: restart postgresql
  tags: pg-config

- name: Add pg_ident.conf file
  template:
    src: postgres/pg_ident.conf.j2
    dest: "/etc/postgresql/{{ pg_version }}/main/pg_ident.conf"
    owner: "{{ pg_user }}"
    group: "{{ pg_user }}"
  notify: reload postgresql
  tags: pg-config

- name: Add postgresql.conf file
  template:
    src: postgres/postgresql.conf.j2
    dest: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
    owner: "{{ pg_user }}"
    group: "{{ pg_user }}"
  notify: restart postgresql
  tags: pg-config

- name: Add start.conf file
  template:
    src: postgres/start.conf.j2
    dest: "/etc/postgresql/{{ pg_version }}/main/start.conf"
    owner: "{{ pg_user }}"
    group: "{{ pg_user }}"
  notify: reload postgresql
  tags: pg-config
