---
- name: Create new databases
  become: true
  become_user: "{{ pg_user }}"
  postgresql_db:
    name: "{{ item.key }}"
  with_dict: "{{ credentials.users }}"
  tags: pg-databases

- name: Connect database, create users, and grant access to own database
  become: true
  become_user: "{{ pg_user }}"
  postgresql_user:
    name: "{{ item.key }}"
    password: "{{ item.value.password }}"
    expires: infinity
  with_dict: "{{ credentials.users }}"
  tags: pg-databases

# https://docs.ansible.com/ansible/latest/modules/postgresql_privs_module.html?highlight=postgres
- name: Grant all privileges
  become: true
  become_user: "{{ pg_user }}"
  postgresql_privs:
    db: "{{ item.key }}"
    privs: ALL
    type: database
    role: "{{ item.key }}"
  with_dict: "{{ credentials.users }}"
  tags: pg-databases
