---
- name: Adds 'pg_stat_statements' extension to all databases
  become: true
  become_user: "{{ pg_user }}"
  postgresql_ext:
    name: pg_stat_statements
    db: "{{ item.value.database }}"
    cascade: true
  with_dict: "{{ credentials.users }}"
  when: (patroni_status.json.role is defined and patroni_status.json.role == "master") or
      (patroni_status.json.role is not defined and role == "master")
