---
- name: Install Monitoring for PostgreSQL Cluster
  hosts: all
  become: true
  gather_facts: True
  vars_files:
    - "{{ inventory_dir }}/credentials.yml"
  roles:
    - serboox.postgres_monitoring
