---
- name: Create users
  hosts: postgres-cluster
  become: true

  vars_files:
    - "{{ inventory_dir }}/credentials.yml"

  tasks:
    - name: Create users
      user:
        name: "{{ item.key }}"
        password: "{{ item.value.password|password_hash('sha512', 65534|random(seed=inventory_hostname)|string) }}"
        groups: "{{ item.value.groups | default(omit) }}"
      when:
        - item.key != pg_user
        - item.key != replica_user_name
      with_dict: "{{ credentials.users }}"
