---
scrape_interval: 5s

postgres_exporter_version: v0.4.7
postgres_exporter_port: 9187

node_exporter_version: v0.15.2
node_exporter_port: 9100

prometheus_version: v2.10.0
prometheus_port: 9090

alertmanager_version: v0.14.0
alertmanager_port: 9093

grafana_version: 5.0.0
grafana_port: 3000
